services:
  ecommercedb:
    image: postgres

  distributedCache:
    image: redis

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:management

  identity:
    image: quay.io/keycloak/keycloak:26.4.1

volumes:
  postgres_ecommercedb:
  seq_data:  