services:
  ecommercedb:
    container_name: ecommercedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommercedb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_ecommercedb:/var/lib/postgresql/data

  distributedCache:
    container_name: distributedCache
    restart: always
    ports:
      - "6379:6379"

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=Password123
    restart: always
    ports:
      - "5341:5341"
      - "9092:80"
    volumes:
      - seq_data:/data

  messagebus:
    container_name: messagebus
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  identity:
    container_name: identity
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://ecommercedb:5432/ecommercedb
      - KC_DB_SCHEMA=identity
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=admin
    restart: always
    depends_on:
      - ecommercedb
    ports:
      - "9090:8080"
    command:
      - start-dev