services:
  ecommercedb:
    image: postgres

  distributedCache:
    image: redis

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:management

volumes:
  postgres_ecommercedb:
  seq_data:  