services:
  ecommercedb:
    container_name: ecommercedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommercedb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_ecommercedb:/var/lib/postgresql/data